name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{matrix.os}}
    container: ${{ matrix.os == 'ubuntu-latest' && 'ghcr.io/f3d-app/f3d-ci' || null }}

    env:
      DISPLAY: :0


    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: 'source'
        submodules: 'true'
        lfs: 'true'

    - name: Build and package F3D
      uses: ./source/.github/actions/f3d-superbuild/
      with:
        f3d_version: origin/master
        os: ${{matrix.os}}

    - name: Deploy Ubuntu release
      if: matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v1
      with:
        repository: f3d-app/f3d
        token: ${{ secrets.SECRET_TOKEN }}
        files: ./build/CMakeCache.txt
        prerelease: true
        tag_name: "nightly"
        name: "Nightly"
